### PR TITLE
Made the identifier used to map an ldap user to a local user configurabl...

### PR DESCRIPTION
**Pull request by trq**
...e.

### CODE REVIEW

**Comment by ccovey** [comment]
So what is the use case for this? wanting to login with email when your primaryKey isn't. If that is it I am going to change the way I do the retrieveByCredentials method to query by key value pairs similar to https://github.com/laravel/framework/blob/master/src/Illuminate/Auth/EloquentUserProvider.php This way it will be much more flexible but you could still do loginById or other things for logging in via the primaryKey (not really much of a use case). Work for the use case you all are thinking about?

**Comment by tortuetorche** [comment]
> If that is it I am going to change the way I do the retrieveByCredentials method to query by key value pairs 

@ccovey Check my pull request #8 please, maybe it's the answer of this issue.

**Comment by trq** [comment]
Any progress on this as yet. @tortuetorche PR looks similar, and either would work for me.

I don't really see how this worked at all without the changes in these PR's.

**Comment by tortuetorche** [comment]
> I don't really see how this worked at all without the changes in these PR's.

@trq You can set in your User model the primary key column to `username` like this :

``` php
class User extends Eloquent
{
    /* ... */
    protected $primaryKey = 'username';
    /* ... */
}
```

But, like I tried to say in my PR #8, with the primary key set to `username`, it's very difficult to add relations to your User model (E.g. attach roles).  Because Eloquent uses by default `id` column as primary key in relations. And packages like [Entrust](https://github.com/Zizaco/entrust) or [Authority](https://github.com/machuga/authority-l4) are setup by default with the `id` primary key for the User model.

**Comment by trq** [comment]
> You can set in your User model the primary key column to username like this:

Yeah I know, but that (as you have pointed out) just leads to trouble.

**Comment by ccovey** [comment]
fixed with https://github.com/ccovey/ldap-auth/commit/3ea727ed1eed2af5ffecd0b58bccc21143b6c23a

**Pull request closed without merging**
