### PR TITLE
Resolve database primary key and LDAP identifier conflicts.

### PR DESCRIPTION
**Pull request by tortuetorche**
This pull request add two type of identifiers. One for your database model and one for your LDAP model.

Usually the LDAP identifier is the `username` attribute, string/varchar datatype.
And the Database identifier is the primary key of your table (`id` column by default), integer datatype.

This feature is really useful when you need to add some relations to your User model (E.g. attaching roles).
Because it allows to avoid conflicts between this two type of identifiers.

Otherwise, when you login with a new user it's OK, but when a user already exists in the database, it's not working.
Because Laravel call the `retrieveByID($identifier)` method with the `id` attribute of the user.
So it can find the user because the`retrieveByID($identifier)` method want a `username` value.

### CODE REVIEW

**Comment by tortuetorche** [comment]
@ccovey Do you plan to merge my pull request ?

**Comment by ccovey** [comment]
Sorry got busy at work, this code won't work as you changed the method signature. Writing something up now that should fix the problem.

**Comment by tortuetorche** [comment]
> you changed the method signature. 

I don't understand what you want to say. This code is OK with my web application.

**Comment by dangerbock** [comment]
this resolves the problem with Entrust ?

**Comment by tortuetorche** [comment]
> this resolves the problem with Entrust ?

I don't use it, I use [Authority](https://github.com/machuga/authority-l4), but I think it should be OK with Entrust. Give it a try please :smile:

**Comment by dangerbock** [comment]
got this error:

Illuminate \ Database \ Eloquent \ MassAssignmentException

id
open: /var/www/dev/intranet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php

```
// assignment to the model, and all others will just be ignored.
if ($this->isFillable($key))
{
$this->setAttribute($key, $value);
}
elseif ($this->totallyGuarded())
{
throw new MassAssignmentException($key);
}
}
```

**Comment by ccovey** [comment]
@tortuetorche the code as you posted is different then the interface that this implements so it will throw an error saying the methods must be compatible. Also using a key that isn't the username will break the retrieveById method because it is called from guard directly and if a auto incremented key is passed in we can't pull from active directory.

**Comment by tortuetorche** [comment]
> the code as you posted is different then the interface that this implements so it will throw an error saying the methods must be compatible. 

You have this error when you run tests ? Because in a web browser, I don't have this kind of issue.
So maybe it's just a bug in the test files ?

**Comment by tortuetorche** [comment]
Here more information on my config.
In `app/config/auth/config.php`:

``` php
return array(
    //code...
    'fields' => array('username' => 'samaccountname', 'displayname' => 'displayName',
        'primarygroup' => 'primarygroups', 'groups' => 'groups', 'firstname' => 'givenName',
        'lastname' => 'cn', 'email' => 'mail'),
);
```

In `app/models/user.php`:

``` php
class User ...
{ 
    //code...
    protected $fillable = array('firstname', 'lastname', 'email', 'displayname');
    //code...
}
```

**Comment by tortuetorche** [comment]
@dangerbock Check my config above, maybe it'll help you.

**Comment by dangerbock** [comment]
hi...i think it's working for me :)
got to test it more but until now no errors :)

**Comment by ccovey** [comment]
@tortuetorche for an example see this paste and the error. http://codepad.viper-7.com/84R5kd . Because we implement https://github.com/laravel/framework/blob/master/src/Illuminate/Auth/UserProviderInterface.php we can't change the method signatures eg add parameters

**Comment by tortuetorche** [comment]
Your code is OK if you rename the `Bar` class to `BarClass` and if you add a `null` default value to the second argument. 
http://codepad.viper-7.com/QLfG4i

**Comment by ccovey** [comment]
@tortuetorche if you have composer set to dev-master or change to 1.0.x if you composer update you will get a fix for this, check out this commit, Let me know if anything doesn't work for you.

https://github.com/ccovey/ldap-auth/commit/3ea727ed1eed2af5ffecd0b58bccc21143b6c23a

**Comment by dangerbock** [comment]
got this error after checkout
screenshot from 2013-09-17 09 58 42

**Comment by dangerbock** [comment]
Just resolved by adding "username" to fillable...but now Auth::attempt always return false

**Comment by dangerbock** [comment]
already working OK :) it was a problem with my user model ... tnkx

**Comment by tortuetorche** [comment]
@ccovey With your commit 3ea727e, when you login with a new user it's OK, but when a user already exists in the database, it's not working.

**Comment by tortuetorche** [comment]
Because Laravel call the `retrieveByID($identifier)` method with the `id` attribute of the user.
So it can find the user because your `retrieveByID($identifier)` method want a `username` value.

**Comment by dangerbock** [comment]
@ccovey hes right
 @tortuetorche any workaround ?

**Comment by tortuetorche** [comment]
> any workaround ?

@dangerbock This pull request #8 :angel:

**Comment by dangerbock** [comment]
@tortuetorche sorry i did't explain myself well...i mean if there is any workarround without changing the package becouse of the composer updates

tnkx mate :)

**Comment by JordanDalton** [comment]
I'm also encountering the MassAssignmentException like dangerbock since updating to the latest version. I do have username added to the $fillables as well.

**Comment by dangerbock** [comment]
@jkdalton i applyed @tortuetorche patch and is working with ldap auth, database model and Entrust

**Comment by tortuetorche** [comment]
> @tortuetorche sorry i did't explain myself well...i mean if there is any workaround without changing the package because of the composer updates

You have to add in `composer.json` file [my](https://github.com/tortuetorche/ldap-auth) fork URL and my `patch-1` branch: 

``` json
{
  ...
  "require": {
    "laravel/framework": "4.*",
    ...
    "ccovey/ldap-auth": "dev-patch-1",
  },
  ...
  "repositories": [{
    "type": "vcs",
    "url": "https://github.com/tortuetorche/ldap-auth"
  }],
  ...
}
```

**Comment by JordanDalton** [comment]
@tortuetorche your solution has resolved my issue.

**Comment by tortuetorche** [comment]
FYI, I've just updated my [`ldap-auth`](https://github.com/tortuetorche/ldap-auth) fork to be compatible with Laravel >= 4.1.26.
Don't forget to read the upgrade notes [here](https://github.com/tortuetorche/ldap-auth/blob/214fe2f10f10470090c4942779f1a1c7840d197c/README.md#model-usage).
It's also fix https://github.com/ccovey/ldap-auth/issues/30.

**Pull request closed without merging**
