### PR TITLE
Update for Laravel 4.2

### PR DESCRIPTION
**Pull request by jordonbrill**
Updating the requirements to work with Laravel 4.1/4/2

### CODE REVIEW

**Comment by ShannonCronin** [comment]
Any updates?

**Comment by syphernl** [comment]
FWIW: Updating just the dependencies isn't sufficient. There are some functions that need to be implemented too, see #42. This is still pretty basic because it doesn't work with "remember me" unlike it did before.

**Comment by tconroy** [comment]
any  updates on this? Would like to use this for a big project that is running 4.2...

**Comment by tortuetorche** [comment]
@tconroy You can use my fork if you want to have this package running with Laravel 4.2:
https://github.com/tortuetorche/ldap-auth

FYI, I use it in production with Laravel 4.1

**Comment by tconroy** [comment]
@tortuetorche cool, thank you for your work on this! Does it bind with a User model for easy reference or does it just handle authenticating with LDAP?

**Pull request closed without merging**
